name: Upload geocodes_bootstrap to Websites

on:
  push:
    branches:
    - geocodes_boostrap

jobs:

  deploy_gecodes_alpha:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        AWS_S3_ENDPOINT: ${{ secrets.S3_GEOCODES_ENDPOINT }}
        SOURCE_DIR: 'alpha/website'      # optional: defaults to entire repository
        DEST_DIR: 'beta/website'
  deploy_geodex_to_geocodes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
        AWS_S3_ENDPOINT: ${{ secrets.S3_GEODEX_ENDPOINT }}
        SOURCE_DIR: 'geodex/website'      # optional: defaults to entire repository
        DEST_DIR: 'geocodes/website'
